# Generated by Django 5.0.4 on 2025-05-15 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0020_alter_paciente_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paciente",
            name="agendamento_fixo",
        ),
    ]
