# Generated by Django 5.0.4 on 2025-05-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transportes", "0003_alter_transporte_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transporte",
            name="motivo_de_transporte",
        ),
        migrations.AlterField(
            model_name="transporte",
            name="descricao_motivo",
            field=models.CharField(max_length=60),
        ),
    ]
