# Generated by Django 5.0.4 on 2025-04-17 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estudantes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="estudante",
            table=None,
        ),
    ]
